services:
  hermes:
    container_name: hermes
    build:
      context: ./src/hermes/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - "80:80"

  pluto:
    container_name: pluto
    build:
      context: ./src/pluto/
      dockerfile: Dockerfile
    networks:
      - net
    env_file:
      - ./src/pluto/.env
    # No ports mapping here—pluto is available only within the Docker network.

networks:
  net:
    name: net
    # Optionally, add internal: true if you want to restrict network access further:
    # internal: true
