services:
  hermes:
    container_name: hermes
    build:
      context: ./src/hermes/
      dockerfile: Dockerfile
    networks:
      - net
    ports:
      - "80:80"

  hecate:
    container_name: hecate
    build:
      context: ./src/hecate/
      dockerfile: Dockerfile
    networks:
      - net
    env_file:
      - ./src/hecate/.env
    # No ports mapping here - hecate is available only within the Docker network.

networks:
  net:
    name: net
    # Optionally, add internal: true if you want to restrict network access further:
    # internal: true
